let itemVars = {
    weapons:{
        rod:{
            weapon:true,
            name:"rod",
            damage:2,
            stunTime:3,
            weight:1,
            type:{
                blunt:true,
                long:true
            }
        },
        club:{
            weapon:true,
            name:"club",
            damage:5,
            stunTime:4,
            weight:1,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:4,
                weight:1,
                type:{
                    blunt:true
                }
            }
        },
        mace:{
            weapon:true,
            name:"mace",
            damage:5,
            stunTime:4,
            weight:1,
            type:{
                blunt:true
            },
            jab:{
                damage:1,
                stunTime:1,
                weight:1,
                type:{
                    blunt:true
                }
            }
        },
        hammer:{
            weapon:true,
            name:"hammer",
            damage:8,
            stunTime:6,
            weight:2,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:3,
                weight:1,
                type:{
                    blunt:true
                }
            }
        },
        maul:{
            weapon:true,
            name:"maul",
            damage:12,
            stunTime:8,
            weight:3,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:4,
                weight:2,
                type:{
                    blunt:true
                }
            }
        },
        rapier:{
            weapon:true,
            name:"rapier",
            damage:2,
            stunTime:2,
            weight:1,
            type:{
                sword:true,
            },
            jab:{
                damage:8,
                stunTime:2,
                weight:1,
                type:{
                    sword:true,
                },
            }
        },
        shortsword:{
            weapon:true,
            name:"shortsword",
            damage:4,
            stunTime:2,
            weight:1,
            type:{
                sword:true,
                edged:true
            }
        },
        longsword:{
            weapon:true,
            name:"longsword",
            damage:8,
            stunTime:3,
            weight:2,
            type:{
                sword:true,
                edged:true
            }
        },
        greatsword:{
            weapon:true,
            name:"greatsword",
            damage:12,
            stunTime:4,
            weight:3,
            type:{
                sword:true,
                edged:true
            }
        },
        handaxe:{
            weapon:true,
            name:"handaxe",
            damage:6,
            stunTime:3,
            weight:1,
            type:{
                edged:true
            },
            jab:{
                damage:1,
                stunTime:1,
                weight:1,
                type:{
                    edged:true
                }
            }
        },
        greataxe:{
            weapon:true,
            name:"greataxe",
            damage:15,
            stunTime:6,
            weight:3,
            type:{
                edged:true
            },
            jab:{
                damage:2,
                stunTime:2,
                weight:3,
                type:{
                    edged:true
                }
            }
        },
        halberd:{
            weapon:true,
            name:"halberd",
            damage:10,
            stunTime:3,
            weight:2,
            type:{
                edged:true,
                long:true
            },
            swing:{
                damage:12,
                stunTime:4,
                weight:3,
                type:{
                    edged:true,
                    long:true
                }
            }
        },
    },
    fuel:{
        oilFlask:{
            usable:true,
            name: "oil flask",
            fuel:true,
            light:2,
            uses:3
        }
    },
    loot:{
        vase:{
            value:5
        },
        pendant:{
            value:10
        }
    }
}